// <auto-generated />
using System;
using ContactConnection.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContactConnection.Infrastructure.Migrations.TenantDb
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260420171530_AddFlowsAndFlowSessions")]
    partial class AddFlowsAndFlowSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContactConnection.Domain.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_agents_email");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.CallInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CallRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("call_record_id");

                    b.Property<Guid?>("CartId")
                        .HasColumnType("uuid")
                        .HasColumnName("cart_id");

                    b.Property<string>("CommitmentEvents")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("commitment_events")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CustomFields")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_fields")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Disposition")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("disposition");

                    b.Property<string>("FlowExecutionState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("flow_execution_state")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<Guid?>("FlowId")
                        .HasColumnType("uuid")
                        .HasColumnName("flow_id");

                    b.Property<int?>("FlowVersion")
                        .HasColumnType("integer")
                        .HasColumnName("flow_version");

                    b.Property<int>("InteractionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("interaction_number");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CallRecordId")
                        .HasDatabaseName("idx_call_interactions_call_record");

                    b.ToTable("call_interactions", (string)null);
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.CallRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("account_number");

                    b.Property<string>("Addresses")
                        .HasColumnType("jsonb")
                        .HasColumnName("addresses");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<string>("ApiResponseCache")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("api_response_cache")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset?>("CallEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("call_end_at");

                    b.Property<DateTimeOffset?>("CallStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("call_start_at");

                    b.Property<string>("CallerId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("caller_id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("CommitmentEvents")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("commitment_events")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("ContactIdExternal")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contact_id_external");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomFields")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_fields")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("FlowExecutionState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("flow_execution_state")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("FulfillmentStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("fulfillment_status");

                    b.Property<int?>("HandleTimeSeconds")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasColumnName("handle_time_seconds")
                        .HasComputedColumnSql("EXTRACT(EPOCH FROM (call_end_at - call_start_at))::integer", true);

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("OverallStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("overall_status");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("payment_status");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("record_type");

                    b.Property<string>("RecordingUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("recording_url");

                    b.Property<string>("SensitiveData")
                        .HasColumnType("jsonb")
                        .HasColumnName("sensitive_data");

                    b.Property<DateTimeOffset?>("SensitiveDataStoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sensitive_data_stored_at");

                    b.Property<DateTimeOffset?>("SensitiveDataWipedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sensitive_data_wiped_at");

                    b.Property<string>("SensitiveWipeReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sensitive_wipe_reason");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<decimal?>("TaxAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("tax_amount");

                    b.Property<string>("TelephonyEvents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("telephony_events")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_amount");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tracking_number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_call_records_tenant");

                    b.HasIndex("AgentId", "CallStartAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_call_records_agent_date");

                    b.HasIndex("CampaignId", "CallStartAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_call_records_campaign_date");

                    b.HasIndex("TenantId", "AccountNumber")
                        .HasDatabaseName("idx_call_records_account");

                    b.HasIndex("TenantId", "AgentId")
                        .HasDatabaseName("idx_call_records_active")
                        .HasFilter("overall_status = 'active'");

                    b.HasIndex("TenantId", "CallerId")
                        .HasDatabaseName("idx_call_records_caller");

                    b.ToTable("call_records", (string)null);
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.Flow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_agent_id");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definition");

                    b.Property<string>("FlowType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("flow_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("idx_flows_tenant_active");

                    b.HasIndex("TenantId", "ClientId", "CampaignId")
                        .HasDatabaseName("idx_flows_tenant_client_campaign");

                    b.ToTable("flows", (string)null);
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.FlowSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<Guid>("CallRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("call_record_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CurrentNodeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("current_node_id");

                    b.Property<string>("ExecutionHistory")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("execution_history");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uuid")
                        .HasColumnName("flow_id");

                    b.Property<int>("FlowVersion")
                        .HasColumnType("integer")
                        .HasColumnName("flow_version");

                    b.Property<Guid>("InteractionId")
                        .HasColumnType("uuid")
                        .HasColumnName("interaction_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VariableStore")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("variable_store");

                    b.HasKey("Id");

                    b.HasIndex("CallRecordId")
                        .HasDatabaseName("idx_flow_sessions_active_call")
                        .HasFilter("status = 'active'");

                    b.HasIndex("CallRecordId", "Status")
                        .HasDatabaseName("idx_flow_sessions_call_record_status");

                    b.HasIndex("TenantId", "AgentId", "StartedAt")
                        .HasDatabaseName("idx_flow_sessions_agent_date");

                    b.ToTable("flow_sessions", (string)null);
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.CallInteraction", b =>
                {
                    b.HasOne("ContactConnection.Domain.Entities.CallRecord", null)
                        .WithMany("Interactions")
                        .HasForeignKey("CallRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.CallRecord", b =>
                {
                    b.Navigation("Interactions");
                });
#pragma warning restore 612, 618
        }
    }
}
