// <auto-generated />
using System;
using ContactConnection.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContactConnection.Infrastructure.Migrations.TenantDb
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260423143630_AddCategoriesAndAttributes")]
    partial class AddCategoriesAndAttributes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContactConnection.Domain.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_agents_email");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.CallInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CallRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("call_record_id");

                    b.Property<Guid?>("CartId")
                        .HasColumnType("uuid")
                        .HasColumnName("cart_id");

                    b.Property<string>("CommitmentEvents")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("commitment_events")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CustomFields")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_fields")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Disposition")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("disposition");

                    b.Property<string>("FlowExecutionState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("flow_execution_state")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<Guid?>("FlowId")
                        .HasColumnType("uuid")
                        .HasColumnName("flow_id");

                    b.Property<int?>("FlowVersion")
                        .HasColumnType("integer")
                        .HasColumnName("flow_version");

                    b.Property<int>("InteractionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("interaction_number");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CallRecordId")
                        .HasDatabaseName("idx_call_interactions_call_record");

                    b.ToTable("call_interactions", (string)null);
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.CallRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("account_number");

                    b.Property<string>("Addresses")
                        .HasColumnType("jsonb")
                        .HasColumnName("addresses");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<string>("ApiResponseCache")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("api_response_cache")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset?>("CallEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("call_end_at");

                    b.Property<DateTimeOffset?>("CallStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("call_start_at");

                    b.Property<string>("CallerId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("caller_id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("Cart")
                        .HasColumnType("jsonb")
                        .HasColumnName("cart");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("CommitmentEvents")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("commitment_events")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("ContactIdExternal")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contact_id_external");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomFields")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_fields")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("FlowExecutionState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("flow_execution_state")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("FulfillmentStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("fulfillment_status");

                    b.Property<int?>("HandleTimeSeconds")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasColumnName("handle_time_seconds")
                        .HasComputedColumnSql("EXTRACT(EPOCH FROM (call_end_at - call_start_at))::integer", true);

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("OverallStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("overall_status");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("payment_status");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("record_type");

                    b.Property<string>("RecordingUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("recording_url");

                    b.Property<string>("SensitiveData")
                        .HasColumnType("jsonb")
                        .HasColumnName("sensitive_data");

                    b.Property<DateTimeOffset?>("SensitiveDataStoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sensitive_data_stored_at");

                    b.Property<DateTimeOffset?>("SensitiveDataWipedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sensitive_data_wiped_at");

                    b.Property<string>("SensitiveWipeReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sensitive_wipe_reason");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<decimal?>("TaxAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("tax_amount");

                    b.Property<string>("TelephonyEvents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("telephony_events")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_amount");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tracking_number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_call_records_tenant");

                    b.HasIndex("AgentId", "CallStartAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_call_records_agent_date");

                    b.HasIndex("CampaignId", "CallStartAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_call_records_campaign_date");

                    b.HasIndex("TenantId", "AccountNumber")
                        .HasDatabaseName("idx_call_records_account");

                    b.HasIndex("TenantId", "AgentId")
                        .HasDatabaseName("idx_call_records_active")
                        .HasFilter("overall_status = 'active'");

                    b.HasIndex("TenantId", "CallerId")
                        .HasDatabaseName("idx_call_records_caller");

                    b.ToTable("call_records", (string)null);
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.Flow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_agent_id");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definition");

                    b.Property<string>("FlowType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("flow_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("idx_flows_tenant_active");

                    b.HasIndex("TenantId", "ClientId", "CampaignId")
                        .HasDatabaseName("idx_flows_tenant_client_campaign");

                    b.ToTable("flows", (string)null);
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.FlowSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<Guid>("CallRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("call_record_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CurrentNodeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("current_node_id");

                    b.Property<string>("ExecutionHistory")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("execution_history");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uuid")
                        .HasColumnName("flow_id");

                    b.Property<int>("FlowVersion")
                        .HasColumnType("integer")
                        .HasColumnName("flow_version");

                    b.Property<Guid>("InteractionId")
                        .HasColumnType("uuid")
                        .HasColumnName("interaction_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VariableStore")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("variable_store");

                    b.HasKey("Id");

                    b.HasIndex("CallRecordId")
                        .HasDatabaseName("idx_flow_sessions_active_call")
                        .HasFilter("status = 'active'");

                    b.HasIndex("CallRecordId", "Status")
                        .HasDatabaseName("idx_flow_sessions_call_record_status");

                    b.HasIndex("TenantId", "AgentId", "StartedAt")
                        .HasDatabaseName("idx_flow_sessions_agent_date");

                    b.ToTable("flow_sessions", (string)null);
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowDeliveryMessage")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_delivery_message");

                    b.Property<bool>("AllowPriceOverride")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_price_override");

                    b.Property<bool>("AllowShipTo")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_ship_to");

                    b.Property<bool>("AutoShip")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_ship");

                    b.Property<string>("AutoShipIntervals")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("auto_ship_intervals")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<bool>("AutoShipOptional")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_ship_optional");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Flags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("flags")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<decimal>("FullPrice")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("full_price");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsUpsell")
                        .HasColumnType("boolean")
                        .HasColumnName("is_upsell");

                    b.Property<string>("MixMatchCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mix_match_code");

                    b.Property<string>("MixMatchPriceBreaks")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("mix_match_price_breaks")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Payments")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("payments")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Personalization")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("personalization")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("QuantityPriceBreaks")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("quantity_price_breaks")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<bool>("ShipMethodPerItem")
                        .HasColumnType("boolean")
                        .HasColumnName("ship_method_per_item");

                    b.Property<string>("ShipMethods")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("ship_methods")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<bool>("ShipToRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("ship_to_required");

                    b.Property<decimal>("Shipping")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("shipping");

                    b.Property<bool>("ShippingExempt")
                        .HasColumnType("boolean")
                        .HasColumnName("shipping_exempt");

                    b.Property<bool>("TaxExempt")
                        .HasColumnType("boolean")
                        .HasColumnName("tax_exempt");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("UpsellClientAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("upsell_client_amount");

                    b.Property<decimal>("UpsellCommission")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("upsell_commission");

                    b.Property<int>("UpsellQty")
                        .HasColumnType("integer")
                        .HasColumnName("upsell_qty");

                    b.Property<int>("UpsellQtyOfEntry")
                        .HasColumnType("integer")
                        .HasColumnName("upsell_qty_of_entry");

                    b.Property<DateTimeOffset?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("MixMatchCode")
                        .HasDatabaseName("ix_offers_mix_match_code");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_offers_product_id");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("ix_offers_tenant_active");

                    b.ToTable("offers", (string)null);
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CallRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("call_record_id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("discount");

                    b.Property<string>("PaymentBreakdowns")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("payment_breakdowns")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<decimal>("SalesTax")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("sales_tax");

                    b.Property<string>("ShipMethod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ship_method");

                    b.Property<DateTimeOffset?>("ShippedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shipped_at");

                    b.Property<decimal>("Shipping")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("shipping");

                    b.Property<string>("ShippingZip")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("shipping_zip");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CallRecordId")
                        .HasDatabaseName("ix_orders_call_record_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_orders_tenant_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_orders_tenant_status");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.OrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AKHISurcharge")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("akhi_surcharge");

                    b.Property<bool>("AutoShip")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_ship");

                    b.Property<int>("AutoShipIntervalDays")
                        .HasColumnType("integer")
                        .HasColumnName("auto_ship_interval_days");

                    b.Property<decimal>("CanadaSurcharge")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("canada_surcharge");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("DeliveryMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("delivery_message");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<decimal>("ExtendedPrice")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("extended_price");

                    b.Property<decimal>("ForeignSurcharge")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("foreign_surcharge");

                    b.Property<string>("FulfillmentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fulfillment_status");

                    b.Property<bool>("IsUpsell")
                        .HasColumnType("boolean")
                        .HasColumnName("is_upsell");

                    b.Property<string>("KitSelections")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("kit_selections")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("MixMatchCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mix_match_code");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<bool>("OnBackOrder")
                        .HasColumnType("boolean")
                        .HasColumnName("on_back_order");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<decimal>("OutlyingUSSurcharge")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("outlying_us_surcharge");

                    b.Property<string>("Payments")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("payments")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("PersonalizationAnswers")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("personalization_answers")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("SalesTax")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("sales_tax");

                    b.Property<string>("ShipMethod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ship_method");

                    b.Property<string>("ShipToJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("ship_to");

                    b.Property<DateTimeOffset?>("ShippedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shipped_at");

                    b.Property<decimal>("Shipping")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("shipping");

                    b.Property<bool>("ShippingExempt")
                        .HasColumnType("boolean")
                        .HasColumnName("shipping_exempt");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku");

                    b.Property<bool>("TaxExempt")
                        .HasColumnType("boolean")
                        .HasColumnName("tax_exempt");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tracking_number");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_lines_order_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_order_lines_tenant_id");

                    b.ToTable("order_lines", (string)null);
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AKHISurcharge")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("akhi_surcharge");

                    b.Property<string>("AliasSKUs")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("alias_skus")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("BackorderMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("backorder_message");

                    b.Property<decimal>("CanadaSurcharge")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("canada_surcharge");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DecrementOnOrder")
                        .HasColumnType("boolean")
                        .HasColumnName("decrement_on_order");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("DiscontinuedMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("discontinued_message");

                    b.Property<int>("ExpectedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("expected_quantity");

                    b.Property<DateOnly?>("ExpectedStockDate")
                        .HasColumnType("date")
                        .HasColumnName("expected_stock_date");

                    b.Property<decimal>("ForeignSurcharge")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("foreign_surcharge");

                    b.Property<string>("InventoryStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("inventory_status");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("keywords")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<int>("MinimumQty")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_qty");

                    b.Property<decimal>("OutlyingUSSurcharge")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("outlying_us_surcharge");

                    b.Property<Guid?>("ParentProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_product_id");

                    b.Property<int>("QtyAvailable")
                        .HasColumnType("integer")
                        .HasColumnName("qty_available");

                    b.Property<int>("QtyLimit")
                        .HasColumnType("integer")
                        .HasColumnName("qty_limit");

                    b.Property<int>("QtyLimitException")
                        .HasColumnType("integer")
                        .HasColumnName("qty_limit_exception");

                    b.Property<int>("QtyReserved")
                        .HasColumnType("integer")
                        .HasColumnName("qty_reserved");

                    b.Property<bool>("ReportingOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("reporting_only");

                    b.Property<bool>("Searchable")
                        .HasColumnType("boolean")
                        .HasColumnName("searchable");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("ParentProductId")
                        .HasDatabaseName("ix_products_parent_product_id");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_products_sku");

                    b.HasIndex("Searchable", "InventoryStatus")
                        .HasDatabaseName("ix_products_searchable_status");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.ProductAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_product_attributes_tenant_id");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_product_attributes_tenant_slug");

                    b.ToTable("product_attributes", (string)null);
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.ProductAttributeValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId")
                        .HasDatabaseName("ix_product_attribute_values_attribute_id");

                    b.ToTable("product_attribute_values", (string)null);
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_product_categories_parent_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_product_categories_tenant_id");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_product_categories_tenant_slug");

                    b.ToTable("product_categories", (string)null);
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.ProductKit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ChildProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_product_id");

                    b.Property<string>("ChoiceSkus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("choice_skus")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<bool>("IsVariable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_variable");

                    b.Property<string>("KitPrompt")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("kit_prompt");

                    b.Property<bool>("MultiSelect")
                        .HasColumnType("boolean")
                        .HasColumnName("multi_select");

                    b.Property<Guid>("ParentProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_product_id");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.HasKey("Id");

                    b.HasIndex("ChildProductId")
                        .HasDatabaseName("ix_product_kits_child");

                    b.HasIndex("ParentProductId")
                        .HasDatabaseName("ix_product_kits_parent");

                    b.ToTable("product_kits", (string)null);
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CallRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("call_record_id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("integer")
                        .HasColumnName("interval_days");

                    b.Property<DateTimeOffset?>("LastShipDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_ship_date");

                    b.Property<DateTimeOffset>("NextShipDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_ship_date");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<Guid>("OriginalOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_order_id");

                    b.Property<Guid>("OriginalOrderLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_order_line_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("ShipmentCount")
                        .HasColumnType("integer")
                        .HasColumnName("shipment_count");

                    b.Property<decimal>("Shipping")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("shipping");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CallRecordId")
                        .HasDatabaseName("ix_subscriptions_call_record_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_subscriptions_tenant_id");

                    b.HasIndex("Status", "NextShipDate")
                        .HasDatabaseName("ix_subscriptions_due");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("product_attribute_assignments", b =>
                {
                    b.Property<Guid>("product_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("attribute_value_id")
                        .HasColumnType("uuid");

                    b.HasKey("product_id", "attribute_value_id");

                    b.HasIndex("attribute_value_id")
                        .HasDatabaseName("ix_product_attribute_assignments_value_id");

                    b.HasIndex("product_id")
                        .HasDatabaseName("ix_product_attribute_assignments_product_id");

                    b.ToTable("product_attribute_assignments", (string)null);
                });

            modelBuilder.Entity("product_category_map", b =>
                {
                    b.Property<Guid>("product_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("category_id")
                        .HasColumnType("uuid");

                    b.HasKey("product_id", "category_id");

                    b.HasIndex("category_id")
                        .HasDatabaseName("ix_product_category_map_category_id");

                    b.HasIndex("product_id")
                        .HasDatabaseName("ix_product_category_map_product_id");

                    b.ToTable("product_category_map", (string)null);
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.CallInteraction", b =>
                {
                    b.HasOne("ContactConnection.Domain.Entities.CallRecord", null)
                        .WithMany("Interactions")
                        .HasForeignKey("CallRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.Offer", b =>
                {
                    b.HasOne("ContactConnection.Domain.Entities.Product", "Product")
                        .WithMany("Offers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.OrderLine", b =>
                {
                    b.HasOne("ContactConnection.Domain.Entities.Order", "Order")
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.Product", b =>
                {
                    b.HasOne("ContactConnection.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ParentProductId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.ProductAttributeValue", b =>
                {
                    b.HasOne("ContactConnection.Domain.Entities.ProductAttribute", "Attribute")
                        .WithMany("Values")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.ProductCategory", b =>
                {
                    b.HasOne("ContactConnection.Domain.Entities.ProductCategory", null)
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.ProductKit", b =>
                {
                    b.HasOne("ContactConnection.Domain.Entities.Product", "Child")
                        .WithMany()
                        .HasForeignKey("ChildProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ContactConnection.Domain.Entities.Product", "Parent")
                        .WithMany("Kits")
                        .HasForeignKey("ParentProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("product_attribute_assignments", b =>
                {
                    b.HasOne("ContactConnection.Domain.Entities.ProductAttributeValue", null)
                        .WithMany()
                        .HasForeignKey("attribute_value_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContactConnection.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("product_category_map", b =>
                {
                    b.HasOne("ContactConnection.Domain.Entities.ProductCategory", null)
                        .WithMany()
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContactConnection.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.CallRecord", b =>
                {
                    b.Navigation("Interactions");
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.Order", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.Product", b =>
                {
                    b.Navigation("Kits");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.ProductAttribute", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.ProductCategory", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
