// <auto-generated />
using System;
using ContactConnection.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContactConnection.Infrastructure.Migrations
{
    [DbContext(typeof(ContactConnectionDbContext))]
    [Migration("20260424140627_AddDataTypes")]
    partial class AddDataTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContactConnection.Domain.Entities.DataType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AggregationFunctions")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("aggregation_functions")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("ClrType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("clr_type");

                    b.Property<string>("DisplayFormat")
                        .HasColumnType("text")
                        .HasColumnName("display_format");

                    b.Property<bool>("IsAggregatable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_aggregatable");

                    b.Property<string>("PostgresType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("postgres_type");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type_name");

                    b.Property<string>("ValidationPattern")
                        .HasColumnType("text")
                        .HasColumnName("validation_pattern");

                    b.HasKey("Id");

                    b.HasIndex("TypeName")
                        .IsUnique()
                        .HasDatabaseName("ix_data_types_type_name");

                    b.ToTable("data_types", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            AggregationFunctions = "[]",
                            ClrType = "System.String",
                            IsAggregatable = false,
                            PostgresType = "text",
                            TypeName = "string"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            AggregationFunctions = "[\"sum\",\"min\",\"max\",\"avg\",\"count\"]",
                            ClrType = "System.Int64",
                            IsAggregatable = true,
                            PostgresType = "bigint",
                            TypeName = "integer"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            AggregationFunctions = "[\"sum\",\"min\",\"max\",\"avg\",\"count\"]",
                            ClrType = "System.Decimal",
                            IsAggregatable = true,
                            PostgresType = "numeric(18,6)",
                            TypeName = "decimal"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            AggregationFunctions = "[\"sum\",\"min\",\"max\",\"avg\",\"count\"]",
                            ClrType = "System.Decimal",
                            DisplayFormat = "C2",
                            IsAggregatable = true,
                            PostgresType = "numeric(10,2)",
                            TypeName = "currency"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            AggregationFunctions = "[\"count\"]",
                            ClrType = "System.Boolean",
                            IsAggregatable = true,
                            PostgresType = "boolean",
                            TypeName = "boolean"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            AggregationFunctions = "[]",
                            ClrType = "System.DateOnly",
                            IsAggregatable = false,
                            PostgresType = "date",
                            TypeName = "date"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            AggregationFunctions = "[]",
                            ClrType = "System.DateTimeOffset",
                            IsAggregatable = false,
                            PostgresType = "timestamptz",
                            TypeName = "datetime"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            AggregationFunctions = "[]",
                            ClrType = "System.Text.Json.JsonElement",
                            IsAggregatable = false,
                            PostgresType = "jsonb",
                            TypeName = "json"
                        });
                });

            modelBuilder.Entity("ContactConnection.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillingContact")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("billing_contact");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomDomain")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("custom_domain");

                    b.Property<string>("FeatureFlags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("feature_flags");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PlanTier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plan_tier");

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("schema_name");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("subdomain");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset?>("TrialExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_expires_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomDomain")
                        .IsUnique()
                        .HasFilter("custom_domain IS NOT NULL");

                    b.HasIndex("SchemaName")
                        .IsUnique();

                    b.HasIndex("Subdomain")
                        .IsUnique();

                    b.ToTable("tenants", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
